name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  build:
    name: Build
    runs-on: blacksmith-32vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"
          cache: "gradle"

      - name: Configure Gradle
        run: |
          mkdir -p ~/.gradle
          echo 'org.gradle.caching=true' >> ~/.gradle/gradle.properties
          echo 'org.gradle.parallel=true' >> ~/.gradle/gradle.properties
          echo 'org.gradle.jvmargs=-Xmx56g -Dfile.encoding=UTF-8 -XX:+UseParallelGC' >> ~/.gradle/gradle.properties
          echo 'android.native.buildOutput=verbose' >> ~/.gradle/gradle.properties

      - name: Configure Signing
        run: |
          echo "storeFile=${{ github.workspace }}/keystore.jks" >> local.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> local.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> local.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> local.properties
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > keystore.jks
  
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew assembleRelease

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: app/build/outputs/apk/release/*.apk
          archive: false
